let a = 5 ;
let b = 10 ;
let c = a + b ;
console.log("a + b = " + c) ;
console.log("a - b = " + a-b) ;
console.log("a * b = "+ a*b) ;
console.log("a / b = "+ a/b) ;
console.log("a % b = "+ a%b) ;
console.log("a ^ b = "+ a**b);
console.log("a++ = "+ a++) ;
console.log("a-- = "+ a--) ;
console.log("++a = "+ ++a) ;
console.log("--a = "+ --a) ;
console.log("a = b : " + (a = b));
console.log("a += b : " + (a += b));
console.log("a -= b : " + (a -= b));
console.log("a *= b : " + (a *= b));
console.log("a /= b : " + (a /= b));
console.log("a %= b : " + (a %= b));
console.log("a **= b : " + (a **= b));
console.log("a == b : " + (a == b));
console.log("a === b : " + (a === b));
console.log("a != b : " + (a != b));
console.log("a !== b : " + (a !== b));
console.log("a > b : " + (a > b));
console.log("a < b : " + (a < b));
console.log("a >= b : " + (a >= b));
console.log("a <= b : " + (a <= b));
console.log("a && b : " + (a && b));
console.log("a || b : " + (a || b));
console.log("!a : " + (!a));
console.log("!b : " + (!b));